### ISSUE TITLE
no such file or directory, open '...angular2-state-machine/core.js.map'

### ISSUE THREAD

**Issue by leydar** [vadym-kukhtin/angular2-state-machine#2]
## Expected Behavior
The state machine should be available.
## Actual Behavior
Using in an Ionic/Angular app it crashes at runtime with the error:
Error: Module build failed: Error: ENOENT: no such file or directory, open '/test/node_modules/angular2-state-machine/core.js.map'
    at Object.<anonymous> (http://localhost:8101/build/vendor.js:123094:7)
    at __webpack_require__ (http://localhost:8101/build/vendor.js:55:30)
    at Object.193 (http://localhost:8101/build/main.js:44:86)
    at __webpack_require__ (http://localhost:8101/build/vendor.js:55:30)
    at Object.268 (http://localhost:8101/build/main.js:173:75)
    at __webpack_require__ (http://localhost:8101/build/vendor.js:55:30)
    at Object.217 (http://localhost:8101/build/main.js:115:73)
    at __webpack_require__ (http://localhost:8101/build/vendor.js:55:30)
    at Object.194 (http://localhost:8101/build/main.js:97:70)
    at __webpack_require__ (http://localhost:8101/build/vendor.js:55:30)

## Steps to Reproduce the Problem

1. Start new Ionic project: ionic start test blank
2. Install state machine: cd ./test && npm i angular2-state-machine
3. Copy example state machine into home.ts
```
import { Component } from '@angular/core';
import { StateMachine, StateEvent } from 'angular2-state-machine/core';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {
  stateMachine: any;
  constructor() { }
  ngOnInit() {
    this.stateMachine = new StateMachine({
        initial: 'test',
        events: [
            new StateEvent({
                 name: 'warn', from: ['green', 'red'], to: 'yellow'
            })
        ]
        });
}}
```
### Specifications
Version: 0.0.5 (tried 1.0.0 but had different issues)
Ionic Framework: 3.9.2
Ionic App Scripts: 3.1.9
Angular Core: 5.2.10
Angular Compiler CLI: 5.2.10
Node: 9.11.1
OS Platform: Linux 4.13

**Comment by PalakjainJain** [comment]
@leydar I am facing the same problem do you have any solution for this.

**Comment by vadym-k21** [comment]
@leydar @PalakjainJain Hi, guys! Sorry, but package itself is deprecated what is stated in description, because for now I have no time to support it anymore

**Comment by leydar** [comment]
Not to worry, @vadym-kukhtin thanks for the update.
